[package]
name    = "elgamal_p256"
version = "0.1.0"
edition = "2021"
autobins = false
[lib]
path = "src/lib.rs"
[dependencies]
cry_rts = { path = "deps/rts-rust" }
dword = { path = "deps/dword" }
num = "0.4.0"
[dev-dependencies]
cry_rts = { path = "deps/rts-rust", features = ["proptest_strategies"] }
dword = { path = "deps/dword", features = ["proptest_strategies"] }
proptest = "1.2"

[[bin]]
name = "cry_test"
path = "exe/main.rs"
