[package]
name    = "cry_rts"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
license-file = "../LICENSE"

[lib]
path = "src/lib.rs"

[dependencies]
num = "0.4.0"
num-bigint = ">=0.4.4"
dword = { path = "../dword" }
proptest = { version = "1.2", optional = true }
rand = { version = "0.8.5", optional = true }

[dev-dependencies]
proptest = "1.2"
rand = "0.8.5"

[features]
# We allow building the proptest-related code paths by enabling the
# `proptest_strategies` feature. This allows downstream dependencies to use
# these strategies in their tests while avoiding the need to depend on
# `proptest` et al. when depending on `cry_rts` in a non-test configuration.
proptest_strategies = ["proptest", "rand"]
